apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: af-connect-demo-pipeline
  name: af-connect-demo-pipeline
spec:
  source:
    type: git
    git:
      ref: dev
      uri: https://github.com/MagnumOpuses/af-connect-cicd.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./af-connect-demo.Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub