apiVersion: v1
kind: BuildConfig
metadata:
    labels:
        app: af-portability-pipeline
    name: af-portability-pipeline
spec:
    source:
        type: git
        git:
            ref: jenkins/deploy
            uri: https://github.com/MagnumOpuses/af-portability.git
    strategy:
        jenkinsPipelineStrategy:
            jenkinsfilePath: ./Jenkinsfile
        type: JenkinsPipeline
    triggers:
        - github:
              secret: secret
          type: GitHub