apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: af-connect-redis
  name: af-connect-redis
spec:
  tags:
  - annotations: {}
    from:
      kind: DockerImage
      name: redis:5.0.9-alpine3.11
    generation: null
    importPolicy: {}
    name: latest