kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: af-connect-test-pipeline
  namespace: af-connect-cicd
  labels:
    app: af-connect-test-pipeline
spec:
  nodeSelector: {}
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/MagnumOpuses/af-portability.git'
      ref: jenkins/modify
  triggers: []
  runPolicy: Serial
status:
  lastVersion: 8
